services:
  mongo-test:
    build:
      context: .
      dockerfile: Dockerfile.mongo_mock
    container_name: mongo-test
    ports:
      - "27018:27017"
    volumes:
      - mongo-test-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass

volumes:
  mongo-test-data:
