apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"walkamile:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"walkamile\")].image","pause":"false"}]
  name: walkamile-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walkamile
  template:
    metadata:
      labels:
        app: walkamile
    spec:
      containers:
        - name: walkamile-backend
          image: walkamile/walkamile-backend:staging
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: walkamile-db-secret
                  key: DB_URL
