apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"walkamile:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"walkamile-backend\")].image","pause":"false"}]
  name: walkamile-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walkamile
  template:
    metadata:
      labels:
        app: walkamile
    spec:
      containers:
        - name: walkamile-backend
          image: walkamile/walkamile-backend:staging
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              #to be set:
              valueFrom:
                secretKeyRef:
                  name: walkamile-db-secret
                  key: DB_URL
            - name: SECRET_KEY
              value: ""
            - name: ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "15"
